server:
  port: 8086

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bappa21ditya/Micro-Configuration-Service
          clone-on-start: true